# Generated by Django 2.2.1 on 2019-05-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, to='contacts_app.Group'),
        ),
    ]
