# Generated by Django 3.2.13 on 2022-06-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0002_alter_person_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name']},
        ),
    ]
