# Generated by Django 3.2.13 on 2023-02-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
