# Generated by Django 3.2.13 on 2023-02-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_created_by', to='contacts_app.user'),
        ),
        migrations.AlterField(
            model_name='email',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_created_by', to='contacts_app.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_created_by', to='contacts_app.user'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_created_by', to='contacts_app.user'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_created_by', to='contacts_app.user'),
        ),
    ]
