# Generated by Django 3.2.13 on 2023-02-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0004_auto_20230212_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='email',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='created_by',
        ),
    ]
